spring:
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.name}?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: ${database.user}
    password: ${database.password}
  jpa:
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: ${email.username}
    password: ${email.password}
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 8000
support:
  email: tungpv@gmail.com



wallet:
  app:
    jwtSecret: 124325
    jwtExpiration: 86400
