spring:
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.name}?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: ${database.user}
    password: ${database.password}
  jpa:
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: ${email.username}
    password: ${email.password}
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 8000
support:
  email: tungpv98@gmail.com

blockchain:
  bitcoin:
    network: testnest
    file-prefix:
    file-location: /home/phan.van.tung/Desktop/DATN/wallet/my-block
#    file-location: ${blockchain.bitcoin.file-location}
    wallet-directory: /home/phan.van.tung/Desktop/DATN/wallet/wallets
#    wallet-directory: ${blockchain.bitcoin.wallet-directory}

wallet:
  app:
    jwtSecret: 124325
    jwtExpiration: 86400

