spring:
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.name}?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: ${database.user}
    password: ${database.password}
  jpa:
    generate-ddl: true

wallet:
  app:
    jwtSecret: 124325
    jwtExpiration: 86400
